sonar.projectKey=DungGramer_constancy
sonar.organization=dunggramer
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=tests/**/*,scripts/**/*
sonar.test.exclusions=tests/**/*

sonar.exclusions=dist/**,node_modules/**,coverage/**,tests/**/*,scripts/**/*
