name: OSV Scanner

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  scan-pr:
    if: github.event_name == 'pull_request'
    name: OSV Scan (PR)
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@c51854704019a247608d928f370c98740469d4b5 # v2.3.5
    with:
      scan-args: |-
        --lockfile=package-lock.json
        ./

  scan-push:
    if: github.event_name == 'push'
    name: OSV Scan (Push)
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@c51854704019a247608d928f370c98740469d4b5 # v2.3.5
    with:
      scan-args: |-
        --lockfile=package-lock.json
        ./
